### ISSUE TITLE
Include explanation and link to docs in several/all files

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/bloodmoon-advanced#5]
I think it would be more user-friendly to include some basic comments and links to docs in the files. More info below.
### Lifecycles.yml
An explanation of the definition of each value/number of:
```[action-name] [start-percentage] [end-percentage] [chance to occur] [max occurences]```
Example of a comment:
```
We assume that you created an action "strike-lightning" to the lifecycle superboss. Our strike-lightning will occur between 100 and 0 percentage of the mob health. 
Every hit has a 100% chance of triggering the action. And the action will execute maximum 3 times during the life cycle.
  superboss:
    actions:
      - strike-lightning 100 0 100 3
      - death 100 0 0.1 1
      - reinforcements 80 0 20 10
```
### Mobs.yml
An explanation of the definition of each value/number of drops:
```
drops explanation: [item-name] [amount] [chance]
Item-name is the item defined from items.yml. Amount is the number of how many of the item is dropped. 
Chance is the chance of the item being dropped upon mob-death. 5.0 = 5%”
    trained-skeleton:
    type: SKELETON
    name: '&5Magic &fSkeleton'
    health: 15.0
    speed: 0.3
    item-drop-chance: 0.0
    items:
      chestplate: skelly-chestplate
      hand: bow
    drops:
      - bow 1 5.0
```
### All files
Include as comment at the beginning of the file with a link to the direct docs explanation of the specific theme/subject.
